fint:
    org-id: novari.no
novari:
    flyt:
        isy-graving:
            dispatch:
                enabled: false
                api-key: ${NOVARI_FLYT_ISY_GRAVING_DISPATCH_API_KEY:}
                api-key-header: ${NOVARI_FLYT_ISY_GRAVING_DISPATCH_API_KEY_HEADER:X-API-KEY}
        file-service-url: http://localhost:8091
        web-instance-gateway:
            check-integration-exists: false
    kafka:
        default-replicas: 1
        topic:
            org-id: novari-no
spring:
    kafka:
        bootstrap-servers: localhost:9092
server:
    port: 8199 # this should be changed to reflects this applications sourceapplication id. if the id is 9, the local port should be 8109

